### recuperar todas la películas
GET  http://localhost:1234/movies

### recuperar una película por id
GET  http://localhost:1234/movies/D28D28A56BC011EE98FFF80DACF4595E

### recuperar 2 película por página 
GET  http://localhost:1234/movies/page?page=1

### recuperar  película por género
GET  http://localhost:1234/movies?genre=Action


### Crear una película
POST http://localhost:1234/movies
Content-Type: application/json 

{
    "sql":"SELECT * FROM users",
    "title": "The 1234",
    "year": 2009,
    "director": "Christo Nola",
    "duration": 500,
    "poster": "https://images-na.ssl-images-amazon.com/images/I/51kz0J%2BZBTL._SY445_.jpg",
    "genre": ["Action"],
    "rate": 9.7
}

### Actualizar una película
PATCH http://localhost:1234/movies/D28D28A56BC011EE98FFF80DACF4595E
Content-Type: application/json

{
  "year": 2002
}

### Borrar una película
DELETE http://localhost:1234/movies/3D7859F36BA611EE98FFF80DACF4595E